import TwoFAService from './service.2fa';
import AddressService from './service.addresses';
import ApiTokensService from './service.api.tokens';
import AuthService from './service.auth';
import CurrencyService from './service.currencies';
import DashboardService from './service.dashboard';
import DexTradeService from './service.dextrade';
import InvoicesService from './service.invoices';
import MemosService from './service.memos';
import PairsService from './service.pairs';
import PreferencesService from './service.preferences';
import ProfileService from './service.profile';
import ProjectService from './service.projects';
import RatesService from './service.rates';
import TradeService from './service.trades';
import TransactionService from './service.transactions';
import UserService from './service.users';
import VaultService from './service.vaults';
import WalletService from './service.wallets';

export const Auth = AuthService;
export const Tokens = ApiTokensService;
export const Projects = ProjectService;
export const Vault = VaultService;
export const Address = AddressService;
export const Currency = CurrencyService;
export const Transaction = TransactionService;
export const Memo = MemosService;
export const Pairs = PairsService;
export const Profile = ProfileService;
export const DexTrade = DexTradeService;
export const Dashboard = DashboardService;
export const User = UserService;
export const Trade = TradeService;
export const TwoFA = TwoFAService;
export const Wallet = WalletService;
export const Invoice = InvoicesService;
export const Rates = RatesService;
export const Preferences = PreferencesService;
